/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APARENT = 8;
  /** RegularExpression Id. */
  int FPARENT = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int ATRIB = 14;
  /** RegularExpression Id. */
  int OP = 15;
  /** RegularExpression Id. */
  int ID = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"int\"",
    "\"bool\"",
    "\"var\"",
    "\";\"",
    "\":=\"",
    "<OP>",
    "<ID>",
  };

}
