/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APARENT = 8;
  /** RegularExpression Id. */
  int FPARENT = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 13;
  /** RegularExpression Id. */
  int VIRGULA = 14;
  /** RegularExpression Id. */
  int OP = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int ATRIB = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int PRINT = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int ID = 25;
  /** RegularExpression Id. */
  int NUMERAL = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"int\"",
    "\"bool\"",
    "\"var\"",
    "\";\"",
    "\",\"",
    "<OP>",
    "\"false\"",
    "\"if\"",
    "\"do\"",
    "\"while\"",
    "\":=\"",
    "\"true\"",
    "\"print\"",
    "\"function\"",
    "\"return\"",
    "<ID>",
    "<NUMERAL>",
  };

}
